// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'foaie_prestatii_mvp';
  static const String PROJECT_VERSION = '0.0.1+94';
  static const String HOLIDAYS_RO_2025 = 'assets/holidays_ro_2025.json';
}
